// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKm0psMCDoqFpdt7BSJ0sorVbRRdyAuy8',
    appId: '1:518302956291:web:f389ef27849e03ab144736',
    messagingSenderId: '518302956291',
    projectId: 'augmented-reality-8328e',
    authDomain: 'augmented-reality-8328e.firebaseapp.com',
    storageBucket: 'augmented-reality-8328e.appspot.com',
    measurementId: 'G-2VPHNBLXEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrO9NQOA3WjNXvN5BCvK3ml0tAZpan6Ms',
    appId: '1:518302956291:android:abf4ea7d1b9b1af3144736',
    messagingSenderId: '518302956291',
    projectId: 'augmented-reality-8328e',
    storageBucket: 'augmented-reality-8328e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8gI6LKiaMtrBp8dyEImCMf-nmaOKqra0',
    appId: '1:518302956291:ios:2acf139d3b7525d6144736',
    messagingSenderId: '518302956291',
    projectId: 'augmented-reality-8328e',
    storageBucket: 'augmented-reality-8328e.appspot.com',
    iosBundleId: 'com.example.augmentedReality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8gI6LKiaMtrBp8dyEImCMf-nmaOKqra0',
    appId: '1:518302956291:ios:2acf139d3b7525d6144736',
    messagingSenderId: '518302956291',
    projectId: 'augmented-reality-8328e',
    storageBucket: 'augmented-reality-8328e.appspot.com',
    iosBundleId: 'com.example.augmentedReality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKm0psMCDoqFpdt7BSJ0sorVbRRdyAuy8',
    appId: '1:518302956291:web:1dcc6a779d22774d144736',
    messagingSenderId: '518302956291',
    projectId: 'augmented-reality-8328e',
    authDomain: 'augmented-reality-8328e.firebaseapp.com',
    storageBucket: 'augmented-reality-8328e.appspot.com',
    measurementId: 'G-EG61X9VFW4',
  );
}
